-- Agendalo Supabase initial schema
-- Run this in Supabase SQL Editor on a fresh project.

begin;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null default '',
  email text not null,
  role text not null default 'owner' check (role in ('admin_platform', 'owner', 'staff')),
  business_id bigint,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists profiles_email_key on public.profiles (lower(email));

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  icon text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.businesses (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  category_id bigint references public.categories(id) on delete set null,
  name text not null,
  slug text not null unique,
  description text,
  phone text,
  email text,
  address text,
  city text,
  country text not null default 'Chile',
  logo_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
  add constraint profiles_business_id_fkey
  foreign key (business_id) references public.businesses(id) on delete set null;

create table if not exists public.business_settings (
  id bigint generated by default as identity primary key,
  business_id bigint not null unique references public.businesses(id) on delete cascade,
  booking_advance_days integer not null default 30,
  min_booking_notice_hours integer not null default 1,
  allow_public_booking boolean not null default true,
  booking_confirmation_required boolean not null default false,
  send_client_calendar_invite boolean not null default true,
  time_zone text not null default 'America/Santiago',
  currency text not null default 'CLP',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.opening_hours (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  day_of_week smallint not null check (day_of_week between 0 and 6),
  is_open boolean not null default true,
  open_time time,
  close_time time,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (business_id, day_of_week)
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  name text not null,
  description text,
  duration_minutes integer not null check (duration_minutes > 0),
  price numeric(12, 2) not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  name text not null,
  email text,
  phone text,
  notes text,
  last_visit_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  client_id bigint references public.clients(id) on delete set null,
  service_id bigint references public.services(id) on delete set null,
  client_name text not null,
  client_email text,
  client_phone text,
  scheduled_at timestamptz not null,
  duration_minutes integer not null check (duration_minutes > 0),
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'completed', 'cancelled', 'no_show')),
  notes text,
  is_from_public boolean not null default false,
  google_event_id text,
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.income_records (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  appointment_id bigint references public.appointments(id) on delete set null,
  description text not null,
  amount numeric(15, 2) not null default 0,
  recorded_at date not null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.expense_categories (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (business_id, name)
);

create table if not exists public.expense_records (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  category_id bigint references public.expense_categories(id) on delete set null,
  description text not null,
  amount numeric(15, 2) not null default 0,
  recorded_at date not null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.supplies (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  name text not null,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (business_id, name)
);

create table if not exists public.supply_transactions (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  supply_id bigint not null references public.supplies(id) on delete cascade,
  quantity numeric(10, 2) not null default 1,
  unit_cost numeric(10, 2) not null default 0,
  total_cost numeric(10, 2) not null default 0,
  purchased_at date not null,
  notes text,
  expense_record_id bigint references public.expense_records(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.google_integrations (
  id bigint generated by default as identity primary key,
  business_id bigint not null unique references public.businesses(id) on delete cascade,
  google_email text,
  access_token text not null,
  refresh_token text,
  token_type text,
  scope text,
  calendar_id text not null default 'primary',
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists businesses_owner_id_idx on public.businesses (owner_id);
create index if not exists businesses_slug_idx on public.businesses (slug);
create index if not exists services_business_id_idx on public.services (business_id);
create index if not exists clients_business_id_idx on public.clients (business_id);
create index if not exists appointments_business_id_scheduled_at_idx on public.appointments (business_id, scheduled_at);
create index if not exists income_records_business_id_recorded_at_idx on public.income_records (business_id, recorded_at);
create index if not exists expense_records_business_id_recorded_at_idx on public.expense_records (business_id, recorded_at);

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger categories_set_updated_at
before update on public.categories
for each row execute function public.set_updated_at();

create trigger businesses_set_updated_at
before update on public.businesses
for each row execute function public.set_updated_at();

create trigger business_settings_set_updated_at
before update on public.business_settings
for each row execute function public.set_updated_at();

create trigger opening_hours_set_updated_at
before update on public.opening_hours
for each row execute function public.set_updated_at();

create trigger services_set_updated_at
before update on public.services
for each row execute function public.set_updated_at();

create trigger clients_set_updated_at
before update on public.clients
for each row execute function public.set_updated_at();

create trigger appointments_set_updated_at
before update on public.appointments
for each row execute function public.set_updated_at();

create trigger income_records_set_updated_at
before update on public.income_records
for each row execute function public.set_updated_at();

create trigger expense_categories_set_updated_at
before update on public.expense_categories
for each row execute function public.set_updated_at();

create trigger expense_records_set_updated_at
before update on public.expense_records
for each row execute function public.set_updated_at();

create trigger supplies_set_updated_at
before update on public.supplies
for each row execute function public.set_updated_at();

create trigger supply_transactions_set_updated_at
before update on public.supply_transactions
for each row execute function public.set_updated_at();

create trigger google_integrations_set_updated_at
before update on public.google_integrations
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    new.email
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.current_business_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select business_id
  from public.profiles
  where id = auth.uid()
    and is_active = true
  limit 1;
$$;

create or replace function public.is_platform_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin_platform'
      and is_active = true
  );
$$;

create or replace function public.owns_business(target_business_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.businesses b
    where b.id = target_business_id
      and b.owner_id = auth.uid()
  );
$$;

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.businesses enable row level security;
alter table public.business_settings enable row level security;
alter table public.opening_hours enable row level security;
alter table public.services enable row level security;
alter table public.clients enable row level security;
alter table public.appointments enable row level security;
alter table public.income_records enable row level security;
alter table public.expense_categories enable row level security;
alter table public.expense_records enable row level security;
alter table public.supplies enable row level security;
alter table public.supply_transactions enable row level security;
alter table public.google_integrations enable row level security;

grant usage on schema public to anon, authenticated;

grant select on public.categories to anon, authenticated;
grant select on public.businesses to anon, authenticated;
grant select on public.business_settings to anon, authenticated;
grant select on public.opening_hours to anon, authenticated;
grant select on public.services to anon, authenticated;

grant select, update on public.profiles to authenticated;
grant insert, select, update, delete on public.businesses to authenticated;
grant insert, select, update, delete on public.business_settings to authenticated;
grant insert, select, update, delete on public.opening_hours to authenticated;
grant insert, select, update, delete on public.services to authenticated;
grant insert, select, update, delete on public.clients to authenticated;
grant insert, select, update, delete on public.appointments to authenticated;
grant insert, select, update, delete on public.income_records to authenticated;
grant insert, select, update, delete on public.expense_categories to authenticated;
grant insert, select, update, delete on public.expense_records to authenticated;
grant insert, select, update, delete on public.supplies to authenticated;
grant insert, select, update, delete on public.supply_transactions to authenticated;
grant insert, select, update, delete on public.google_integrations to authenticated;

grant usage, select on all sequences in schema public to authenticated;

create policy "profiles_select_own_or_admin"
on public.profiles for select
to authenticated
using (id = auth.uid() or public.is_platform_admin());

create policy "profiles_update_own_or_admin"
on public.profiles for update
to authenticated
using (id = auth.uid() or public.is_platform_admin())
with check (id = auth.uid() or public.is_platform_admin());

create policy "categories_select_all"
on public.categories for select
to anon, authenticated
using (true);

create policy "categories_admin_write"
on public.categories for all
to authenticated
using (public.is_platform_admin())
with check (public.is_platform_admin());

create policy "businesses_select_private_or_public"
on public.businesses for select
to anon, authenticated
using (
  public.is_platform_admin()
  or owner_id = auth.uid()
  or id = public.current_business_id()
  or (
    is_active = true
    and exists (
      select 1
      from public.business_settings bs
      where bs.business_id = businesses.id
        and bs.allow_public_booking = true
    )
  )
);

create policy "businesses_insert_own"
on public.businesses for insert
to authenticated
with check (owner_id = auth.uid() or public.is_platform_admin());

create policy "businesses_update_own"
on public.businesses for update
to authenticated
using (owner_id = auth.uid() or id = public.current_business_id() or public.is_platform_admin())
with check (owner_id = auth.uid() or id = public.current_business_id() or public.is_platform_admin());

create policy "tenant_select_business_settings"
on public.business_settings for select
to authenticated
using (business_id = public.current_business_id() or public.owns_business(business_id) or public.is_platform_admin());

create policy "public_select_booking_settings"
on public.business_settings for select
to anon
using (allow_public_booking = true);

create policy "tenant_write_business_settings"
on public.business_settings for all
to authenticated
using (business_id = public.current_business_id() or public.owns_business(business_id) or public.is_platform_admin())
with check (business_id = public.current_business_id() or public.owns_business(business_id) or public.is_platform_admin());

create policy "tenant_select_opening_hours"
on public.opening_hours for select
to authenticated
using (business_id = public.current_business_id() or public.owns_business(business_id) or public.is_platform_admin());

create policy "public_select_opening_hours"
on public.opening_hours for select
to anon
using (
  exists (
    select 1
    from public.business_settings bs
    where bs.business_id = opening_hours.business_id
      and bs.allow_public_booking = true
  )
);

create policy "tenant_write_opening_hours"
on public.opening_hours for all
to authenticated
using (business_id = public.current_business_id() or public.owns_business(business_id) or public.is_platform_admin())
with check (business_id = public.current_business_id() or public.owns_business(business_id) or public.is_platform_admin());

create policy "tenant_select_services"
on public.services for select
to authenticated
using (business_id = public.current_business_id() or public.owns_business(business_id) or public.is_platform_admin());

create policy "public_select_active_services"
on public.services for select
to anon
using (
  is_active = true
  and exists (
    select 1
    from public.business_settings bs
    join public.businesses b on b.id = bs.business_id
    where bs.business_id = services.business_id
      and bs.allow_public_booking = true
      and b.is_active = true
  )
);

create policy "tenant_write_services"
on public.services for all
to authenticated
using (business_id = public.current_business_id() or public.owns_business(business_id) or public.is_platform_admin())
with check (business_id = public.current_business_id() or public.owns_business(business_id) or public.is_platform_admin());

create policy "tenant_crud_clients"
on public.clients for all
to authenticated
using (business_id = public.current_business_id() or public.is_platform_admin())
with check (business_id = public.current_business_id() or public.is_platform_admin());

create policy "tenant_crud_appointments"
on public.appointments for all
to authenticated
using (business_id = public.current_business_id() or public.is_platform_admin())
with check (business_id = public.current_business_id() or public.is_platform_admin());

create policy "tenant_crud_income_records"
on public.income_records for all
to authenticated
using (business_id = public.current_business_id() or public.is_platform_admin())
with check (business_id = public.current_business_id() or public.is_platform_admin());

create policy "tenant_crud_expense_categories"
on public.expense_categories for all
to authenticated
using (business_id = public.current_business_id() or public.is_platform_admin())
with check (business_id = public.current_business_id() or public.is_platform_admin());

create policy "tenant_crud_expense_records"
on public.expense_records for all
to authenticated
using (business_id = public.current_business_id() or public.is_platform_admin())
with check (business_id = public.current_business_id() or public.is_platform_admin());

create policy "tenant_crud_supplies"
on public.supplies for all
to authenticated
using (business_id = public.current_business_id() or public.is_platform_admin())
with check (business_id = public.current_business_id() or public.is_platform_admin());

create policy "tenant_crud_supply_transactions"
on public.supply_transactions for all
to authenticated
using (business_id = public.current_business_id() or public.is_platform_admin())
with check (business_id = public.current_business_id() or public.is_platform_admin());

create policy "tenant_crud_google_integrations"
on public.google_integrations for all
to authenticated
using (business_id = public.current_business_id() or public.is_platform_admin())
with check (business_id = public.current_business_id() or public.is_platform_admin());

insert into public.categories (name, slug, icon)
values
  ('Barberia y Peluqueria', 'barberia-y-peluqueria', 'scissors'),
  ('Salud y Medicina', 'salud-y-medicina', 'health'),
  ('Deportes y Gimnasio', 'deportes-y-gimnasio', 'fitness'),
  ('Asesoria y Consultoria', 'asesoria-y-consultoria', 'briefcase'),
  ('Estetica y Spa', 'estetica-y-spa', 'sparkles'),
  ('Educacion y Clases', 'educacion-y-clases', 'book'),
  ('Otros', 'otros', 'more')
on conflict (slug) do nothing;

commit;
