-- Subscription plans and active business subscriptions.
-- Trial is represented as a subscription status over the Premium plan.

begin;

create table if not exists public.plans (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  description text,
  price_clp integer not null default 0 check (price_clp >= 0),
  billing_period_days integer not null default 30 check (billing_period_days > 0),
  features jsonb not null default '{}'::jsonb,
  limits jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.business_subscriptions (
  id bigint generated by default as identity primary key,
  business_id bigint not null unique references public.businesses(id) on delete cascade,
  plan_id bigint not null references public.plans(id),
  status text not null default 'trialing' check (status in ('trialing', 'active', 'past_due', 'expired', 'cancelled')),
  starts_at timestamptz not null default now(),
  ends_at timestamptz not null,
  trial_ends_at timestamptz,
  cancelled_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists business_subscriptions_business_id_idx
on public.business_subscriptions (business_id);

create index if not exists business_subscriptions_plan_id_idx
on public.business_subscriptions (plan_id);

create index if not exists business_subscriptions_status_ends_at_idx
on public.business_subscriptions (status, ends_at);

drop trigger if exists plans_set_updated_at on public.plans;
create trigger plans_set_updated_at
before update on public.plans
for each row execute function public.set_updated_at();

drop trigger if exists business_subscriptions_set_updated_at on public.business_subscriptions;
create trigger business_subscriptions_set_updated_at
before update on public.business_subscriptions
for each row execute function public.set_updated_at();

alter table public.plans enable row level security;
alter table public.business_subscriptions enable row level security;

grant select on public.plans to anon, authenticated;
grant insert, update, delete on public.plans to authenticated;
grant select, insert, update, delete on public.business_subscriptions to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "plans_select_active" on public.plans;
create policy "plans_select_active"
on public.plans for select
to anon, authenticated
using (is_active = true or public.is_platform_admin());

drop policy if exists "plans_admin_write" on public.plans;
create policy "plans_admin_write"
on public.plans for all
to authenticated
using (public.is_platform_admin())
with check (public.is_platform_admin());

drop policy if exists "tenant_select_business_subscriptions" on public.business_subscriptions;
create policy "tenant_select_business_subscriptions"
on public.business_subscriptions for select
to authenticated
using (
  business_id = public.current_business_id()
  or public.owns_business(business_id)
  or public.is_platform_admin()
);

drop policy if exists "tenant_insert_business_subscriptions" on public.business_subscriptions;
create policy "tenant_insert_business_subscriptions"
on public.business_subscriptions for insert
to authenticated
with check (
  business_id = public.current_business_id()
  or public.owns_business(business_id)
  or public.is_platform_admin()
);

drop policy if exists "admin_update_business_subscriptions" on public.business_subscriptions;
create policy "admin_update_business_subscriptions"
on public.business_subscriptions for update
to authenticated
using (public.is_platform_admin())
with check (public.is_platform_admin());

drop policy if exists "admin_delete_business_subscriptions" on public.business_subscriptions;
create policy "admin_delete_business_subscriptions"
on public.business_subscriptions for delete
to authenticated
using (public.is_platform_admin());

insert into public.plans (
  code,
  name,
  description,
  price_clp,
  billing_period_days,
  features,
  limits,
  display_order
)
values
  (
    'agenda',
    'Agenda',
    'Agenda, reservas publicas, clientes, servicios, Google Calendar e ingresos simples.',
    9990,
    30,
    '{
      "agenda": true,
      "public_booking": true,
      "clients": true,
      "services": true,
      "google_calendar": true,
      "income_summary": true,
      "manual_income": false,
      "expenses": false,
      "balance": false,
      "supplies": false,
      "inventory": false
    }'::jsonb,
    '{}'::jsonb,
    1
  ),
  (
    'premium',
    'Premium',
    'Todo Agenda mas balance, ingresos manuales, egresos, insumos e inventario.',
    19990,
    30,
    '{
      "agenda": true,
      "public_booking": true,
      "clients": true,
      "services": true,
      "google_calendar": true,
      "income_summary": true,
      "manual_income": true,
      "expenses": true,
      "balance": true,
      "supplies": true,
      "inventory": true
    }'::jsonb,
    '{}'::jsonb,
    2
  )
on conflict (code) do update
set
  name = excluded.name,
  description = excluded.description,
  price_clp = excluded.price_clp,
  billing_period_days = excluded.billing_period_days,
  features = excluded.features,
  limits = excluded.limits,
  is_active = true,
  display_order = excluded.display_order;

insert into public.business_subscriptions (
  business_id,
  plan_id,
  status,
  starts_at,
  ends_at,
  trial_ends_at,
  notes
)
select
  b.id,
  p.id,
  'trialing',
  now(),
  now() + interval '14 days',
  now() + interval '14 days',
  'Backfill inicial: prueba Premium de 14 dias.'
from public.businesses b
cross join public.plans p
where p.code = 'premium'
  and not exists (
    select 1
    from public.business_subscriptions bs
    where bs.business_id = b.id
  );

commit;
