-- Store initial registration intent without creating subscriptions yet.

begin;

create table if not exists public.registration_requests (
  id bigint generated by default as identity primary key,
  profile_id uuid not null unique references public.profiles(id) on delete cascade,
  requested_plan_code text not null check (requested_plan_code in ('trial', 'agenda', 'premium')),
  requested_plan_id bigint references public.plans(id) on delete set null,
  status text not null check (status in ('pending_approval', 'pending_payment', 'instructions_sent', 'approved', 'cancelled')),
  approved_at timestamptz,
  activation_deadline timestamptz,
  payment_confirmed_at timestamptz,
  payment_confirmed_by uuid references public.profiles(id) on delete set null,
  instructions_sent_at timestamptz,
  included_trial_days integer not null check (included_trial_days >= 0),
  purchased_period_days integer not null default 0 check (purchased_period_days >= 0),
  plan_price_snapshot integer check (plan_price_snapshot is null or plan_price_snapshot >= 0),
  cancelled_at timestamptz,
  cancelled_by uuid references public.profiles(id) on delete set null,
  admin_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists registration_requests_status_idx
on public.registration_requests (status);

create index if not exists registration_requests_requested_plan_code_idx
on public.registration_requests (requested_plan_code);

create index if not exists registration_requests_created_at_idx
on public.registration_requests (created_at desc);

drop trigger if exists registration_requests_set_updated_at on public.registration_requests;
create trigger registration_requests_set_updated_at
before update on public.registration_requests
for each row execute function public.set_updated_at();

alter table public.registration_requests enable row level security;

revoke all on public.registration_requests from public;
revoke all on public.registration_requests from anon;
revoke all on public.registration_requests from authenticated;
grant select on public.registration_requests to authenticated;
grant select, insert, update on public.registration_requests to service_role;
grant usage, select on sequence public.registration_requests_id_seq to service_role;

drop policy if exists "registration_requests_select_own_or_admin" on public.registration_requests;
create policy "registration_requests_select_own_or_admin"
on public.registration_requests for select
to authenticated
using (
  profile_id = auth.uid()
  or public.is_platform_admin()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  requested_plan_code_value text;
  lookup_plan_code text;
  requested_plan_row public.plans%rowtype;
  registration_status_value text;
  purchased_period_days_value integer := 0;
  plan_price_snapshot_value integer := 0;
begin
  insert into public.profiles (id, name, email, is_active)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    new.email,
    false
  )
  on conflict (id) do nothing;

  requested_plan_code_value := lower(trim(coalesce(new.raw_user_meta_data->>'requested_plan_code', 'trial')));

  if requested_plan_code_value not in ('trial', 'agenda', 'premium') then
    requested_plan_code_value := 'trial';
  end if;

  lookup_plan_code := case
    when requested_plan_code_value = 'trial' then 'premium'
    else requested_plan_code_value
  end;

  select *
  into requested_plan_row
  from public.plans
  where code = lookup_plan_code
    and is_active = true
  limit 1;

  if requested_plan_code_value in ('agenda', 'premium') then
    if requested_plan_row.id is null then
      raise exception 'Plan solicitado no disponible.';
    end if;

    registration_status_value := 'pending_payment';
    purchased_period_days_value := requested_plan_row.billing_period_days;
    plan_price_snapshot_value := requested_plan_row.price_clp;
  else
    registration_status_value := 'pending_approval';
    purchased_period_days_value := 0;
    plan_price_snapshot_value := 0;
  end if;

  insert into public.registration_requests (
    profile_id,
    requested_plan_code,
    requested_plan_id,
    status,
    included_trial_days,
    purchased_period_days,
    plan_price_snapshot
  )
  values (
    new.id,
    requested_plan_code_value,
    requested_plan_row.id,
    registration_status_value,
    14,
    purchased_period_days_value,
    plan_price_snapshot_value
  )
  on conflict (profile_id) do nothing;

  return new;
end;
$$;

commit;
