-- Store subscription requests without changing the current business subscription.

begin;

create table if not exists public.subscription_requests (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  request_type text not null check (request_type in ('subscription_activation', 'subscription_renewal', 'subscription_change')),
  status text not null default 'pending' check (status in ('pending', 'instructions_sent', 'completed', 'cancelled')),
  current_plan_id bigint references public.plans(id) on delete set null,
  requested_plan_id bigint not null references public.plans(id),
  current_subscription_status text check (current_subscription_status is null or current_subscription_status in ('trialing', 'active', 'past_due', 'expired', 'cancelled')),
  current_ends_at timestamptz,
  remaining_days_snapshot integer not null default 0 check (remaining_days_snapshot >= 0),
  requested_period_days integer not null check (requested_period_days > 0),
  notes text,
  admin_notes text,
  instructions_sent_at timestamptz,
  completed_at timestamptz,
  cancelled_at timestamptz,
  completed_by uuid references public.profiles(id) on delete set null,
  cancelled_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists subscription_requests_business_id_idx
on public.subscription_requests (business_id);

create index if not exists subscription_requests_profile_id_idx
on public.subscription_requests (profile_id);

create index if not exists subscription_requests_status_idx
on public.subscription_requests (status);

create index if not exists subscription_requests_created_at_idx
on public.subscription_requests (created_at desc);

create index if not exists subscription_requests_request_type_idx
on public.subscription_requests (request_type);

create unique index if not exists subscription_requests_one_open_per_business_idx
on public.subscription_requests (business_id)
where status in ('pending', 'instructions_sent');

drop trigger if exists subscription_requests_set_updated_at on public.subscription_requests;
create trigger subscription_requests_set_updated_at
before update on public.subscription_requests
for each row execute function public.set_updated_at();

alter table public.subscription_requests enable row level security;

revoke all on public.subscription_requests from public;
revoke all on public.subscription_requests from anon;
revoke all on public.subscription_requests from authenticated;
grant select on public.subscription_requests to authenticated;

drop policy if exists "subscription_requests_select_own_or_admin" on public.subscription_requests;
create policy "subscription_requests_select_own_or_admin"
on public.subscription_requests for select
to authenticated
using (
  public.is_platform_admin()
  or business_id = public.current_business_id()
);

create or replace function public.create_subscription_request(
  target_plan_code text,
  target_notes text default null
)
returns public.subscription_requests
language plpgsql
security definer
set search_path = public
as $$
declare
  profile_row public.profiles%rowtype;
  business_row public.businesses%rowtype;
  requested_plan_row public.plans%rowtype;
  current_subscription_row public.business_subscriptions%rowtype;
  request_type_value text;
  remaining_days_value integer := 0;
  inserted_request public.subscription_requests%rowtype;
begin
  if auth.uid() is null then
    raise exception 'Sesion no disponible.';
  end if;

  select *
  into profile_row
  from public.profiles
  where id = auth.uid();

  if profile_row.id is null then
    raise exception 'Perfil no encontrado.';
  end if;

  if profile_row.is_active is not true then
    raise exception 'La cuenta no esta activa.';
  end if;

  if profile_row.business_id is null then
    raise exception 'El perfil no tiene un negocio configurado.';
  end if;

  select *
  into business_row
  from public.businesses
  where id = profile_row.business_id;

  if business_row.id is null then
    raise exception 'Negocio no encontrado.';
  end if;

  if business_row.owner_id <> auth.uid() then
    raise exception 'No puedes crear solicitudes para un negocio que no te pertenece.';
  end if;

  select *
  into requested_plan_row
  from public.plans
  where code = lower(trim(target_plan_code))
    and is_active = true
  limit 1;

  if requested_plan_row.id is null then
    raise exception 'Plan solicitado no disponible.';
  end if;

  if exists (
    select 1
    from public.subscription_requests request
    where request.business_id = business_row.id
      and request.status in ('pending', 'instructions_sent')
  ) then
    raise exception 'Ya existe una solicitud de suscripcion abierta para este negocio.';
  end if;

  select *
  into current_subscription_row
  from public.business_subscriptions subscription
  where subscription.business_id = business_row.id
  limit 1;

  if current_subscription_row.id is not null
    and current_subscription_row.ends_at > now()
  then
    remaining_days_value := ceil(extract(epoch from (current_subscription_row.ends_at - now())) / 86400)::integer;
  end if;

  if current_subscription_row.id is null
    or current_subscription_row.ends_at <= now()
    or current_subscription_row.status <> 'active'
  then
    request_type_value := 'subscription_activation';
  elsif current_subscription_row.plan_id = requested_plan_row.id then
    request_type_value := 'subscription_renewal';
  else
    request_type_value := 'subscription_change';
  end if;

  insert into public.subscription_requests (
    business_id,
    profile_id,
    request_type,
    status,
    current_plan_id,
    requested_plan_id,
    current_subscription_status,
    current_ends_at,
    remaining_days_snapshot,
    requested_period_days,
    notes
  )
  values (
    business_row.id,
    profile_row.id,
    request_type_value,
    'pending',
    current_subscription_row.plan_id,
    requested_plan_row.id,
    current_subscription_row.status,
    current_subscription_row.ends_at,
    remaining_days_value,
    requested_plan_row.billing_period_days,
    nullif(trim(target_notes), '')
  )
  returning * into inserted_request;

  return inserted_request;
end;
$$;

revoke all on function public.create_subscription_request(text, text) from public;
grant execute on function public.create_subscription_request(text, text) to authenticated;

commit;
